---
title: "Tidy_data"
author: "Shafayet Shariar Hossain"
date: "2/23/2022"
output: html_document
---

```{r}
library(tidyverse)

haireye <- as_tibble(HairEyeColor) |> 
  count(Hair, Eye, wt = n) |> 
  rename(hair = Hair, eye = Eye)

```

```{r}

haireye |>
  mutate(eye = str_c(eye, "_eyed"))|>
  pivot_wider(id_cols = hair, names_from = eye, values_from = n)
```

```{r}

haireye_untidy <- haireye |>
  mutate(eye = str_c(eye, "_eyed"))|>
  pivot_wider(id_cols = hair, names_from = eye, values_from = n)


```



```{r}
haireye_tidy <- haireye_untidy |>
  pivot_longer(cols = c(names(haireye_untidy)[2:5]),
               names_to = 'eye',
               values_to = 'n')
```


```{r}

haireye |> 
  pivot_wider(id_cols     = hair, 
              names_from  = eye, 
              values_from = n)


```



# MUltivariate Pivoting


```{r}
library(tidyverse)

WHO <- who |>
    select(country:year, starts_with("new_")) |> 
    rename_with(~ stringr::str_replace(.x, "f", "f_"), starts_with("new_")) |> 
    rename_with(~ stringr::str_replace(.x, "m", "m_"), starts_with("new_"))
knitr::kable(WHO, rownames = FALSE)

```



```{r}


WHO <- WHO|>
  pivot_longer(cols = new_sp_m_014:new_ep_f_65,
               names_to = c('Diagnosis','Gender','Age'),
               names_prefix = 'new_',
               names_sep = '_',
               values_to = 'count')
```




```{r}

fam_dat <- tribble(
  ~family,  ~dob_child1,  ~dob_child2, ~gender_child1, ~gender_child2,
       1L, "1998-11-26", "2000-01-29",             1L,             2L,
       2L, "1996-06-22",           NA,             2L,             NA,
       3L, "2002-07-11", "2004-04-05",             2L,             2L,
       4L, "2004-10-10", "2009-08-27",             1L,             1L,
       5L, "2000-12-05", "2005-02-28",             2L,             1L,
)
fam_dat <- fam_dat |> mutate_at(vars(starts_with("dob")), parse_date)
fam_dat


```





```{r}

fam_dat_long <- fam_dat |> 
  pivot_longer(
    cols = -family,
    names_to = c(".value", "child"), 
    names_sep = "_", 
    values_drop_na = TRUE
  ) |> 
  mutate(child = stringr::str_replace(child, "child", "")) |> 
  mutate(child = as.integer(child))


```

