---
title: "Lab 03 Explore gapminder with ggplot2 and dplyr"
author: "Shafayet Shariar Hossain"
date: "02/08/2022"
output: html_document
---

## Load packages and data

```{r setup, message=FALSE}
library(tidyverse)
library(gapminder)
```


## Exercises

### Exercise 1.1


```{r filter gapminder to 3 countries in the 1970's}

filter(gapminder, country %in% c('Bangladesh','France','United States') & year %in% c(1970:1979))

```

### Exercise 1.2

```{r use the pipe operator |> to first do the above filter and then select the “country” and “gdpPercap” variables.}


gapminder |> 
  filter(country %in% c('Bangladesh','France','United States')) |> 
  filter(year %in% c(1970:1979)) |> 
  select(country, gdpPercap)

```

### Exercise 1.3

```{r a new variable in gapminder for the change in life expectancy from the previous measurement for that country}


new_gapminder <- gapminder |> 
  arrange(year) |> 
  group_by(country) |> 
  mutate(lifeExp_change = lifeExp - lag(lifeExp)) |> 
  filter(lifeExp_change < 0)

new_gapminder

```

### Exercise 1.4

```{r max GDP per capita experienced by each country}

gapminder |> 
  group_by(country) |> 
  filter(gdpPercap == max(gdpPercap))


```

### Exercise 1.5

```{r a scatterplot of Canada’s life expectancy vs. GDP per capita}


ggplot(gapminder |> 
  filter(country %in% 'Canada')) +
  aes(x = gdpPercap, y = lifeExp) +
  geom_point()+
  scale_x_continuous(trans = 'log10', labels = scales::dollar_format())


```




### Exercise 2.1


```{r a summary table of descriptive statistics for two quantative variables}

# I have chosen the gapminder data set. And the chosen variables are
# lifeExp & population


gapminder |>
  summarize(
    across(lifeExp,pop,
           list(
             mean = \(x) mean(x),
             median = \(x) median(x)
           ))
  )


```

### Exercise 2.2

Remove this text, and add your answer for Exercise 5 here.

```{r plastic-waste-mismanaged}



```

### Exercise 2.3

Remove this text, and add your answer for Exercise 6 here.

```{r plastic-waste-mismanaged-continent}



```

### Exercise 2.4




### Exercise 3.1

```{r relationship between plastic waste per capita and mismanaged plastic waste per capita}



```

### Exercise 3.2

```{r Color the points in the scatterplot by continent}



```


### Exercise 3.3

```{r }




```


```{r }



```



### Exercise 4

Remove this text, and add your answer for Exercise 8 here.

```{r recreate-viz}

  

```

